import 'dart:async';
import 'dart:convert';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'identification_service.dart';
import 'species_catalog.dart';

/// Where a riddle came from. Shown in debug builds so it is obvious during a
/// demo whether the fine-tuned model actually ran.
enum RiddleSource {
  /// Freshly generated by the Phi-3 LoRA on the server.
  model,

  /// A previously generated model riddle shipped with the app.
  cached,

  /// Assembled from the species' visual features on-device. Never as good, but
  /// it means the game still works on a hilltop with no signal.
  composed,
}

class Riddle {
  const Riddle({
    required this.lines,
    required this.species,
    required this.source,
  });

  final List<String> lines;
  final Species species;
  final RiddleSource source;

  String get text => lines.join('\n');

  bool get isWellFormed =>
      lines.length == 4 && lines.last.trimRight().endsWith('?');
}

/// Supplies a riddle for a species, in order of preference:
///
/// 1. the fine-tuned Phi-3 model, via the API — different every time;
/// 2. a bundled cache of riddles the same model produced earlier;
/// 3. an on-device composer built from the species' visual features.
///
/// Only step 1 needs a network, so the treasure-hunt mechanic keeps working
/// offline — it just stops being novel.
class RiddleRepository {
  RiddleRepository({
    required IdentificationService identification,
    Random? random,
  })  : _identification = identification,
        _random = random ?? Random();

  final IdentificationService _identification;
  final Random _random;

  static const String cacheAsset = 'assets/riddles/nepal40_riddles.json';

  Map<String, List<List<String>>>? _cache;

  /// Loads the bundled riddle cache. Missing file is fine — [riddleFor] then
  /// falls through to the composer.
  ///
  /// Bounded by a timeout on purpose: for an asset that is not bundled, the
  /// asset bundle can return a future that never completes, and callers awaiting
  /// this would hang rather than fall back.
  Future<void> warmCache({
    Duration timeout = const Duration(seconds: 3),
  }) async {
    if (_cache != null) return;
    try {
      final raw = await rootBundle.loadString(cacheAsset).timeout(timeout);
      final json = jsonDecode(raw) as Map<String, dynamic>;
      final entries = (json['riddles'] as Map<String, dynamic>?) ?? {};
      _cache = {
        for (final e in entries.entries)
          e.key: (e.value as List)
              .map((r) => (r as List).cast<String>())
              .toList(),
      };
      debugPrint('[plantgo] riddle cache: ${_cache!.length} species');
    } on Object catch (e) {
      _cache = {};
      debugPrint('[plantgo] no bundled riddle cache ($e); will compose locally');
    }
  }

  Future<Riddle> riddleFor(Species species, {bool allowNetwork = true}) async {
    if (allowNetwork) {
      final generated = await _identification.riddleFor(species);
      if (generated != null) {
        final lines = generated.lines;
        if (lines.length == 4) {
          return Riddle(
              lines: lines, species: species, source: RiddleSource.model);
        }
        debugPrint('[plantgo] model riddle had ${lines.length} lines; falling back');
      }
    }

    await warmCache();
    final cached = _cache?[species.scientificName];
    if (cached != null && cached.isNotEmpty) {
      return Riddle(
        lines: cached[_random.nextInt(cached.length)],
        species: species,
        source: RiddleSource.cached,
      );
    }

    return Riddle(
      lines: compose(species, _random),
      species: species,
      source: RiddleSource.composed,
    );
  }

  /// Deterministic-ish 4-line riddle from the species' visual features.
  ///
  /// Kept simple on purpose: it must never name the plant and must always end
  /// in a question, because those are the two rules the game depends on.
  @visibleForTesting
  static List<String> compose(Species species, [Random? random]) {
    final rng = random ?? Random();
    final features = [...species.visualFeatures]..shuffle(rng);

    String clause(String feature) {
      var f = feature.trim();
      // Features are written as noun phrases ("Heart-shaped leaf with a tail");
      // lower-case the first letter so they read inside a sentence.
      if (f.isNotEmpty) f = f[0].toLowerCase() + f.substring(1);
      return f;
    }

    final openings = [
      'Look for ${clause(features[0])},',
      'I show ${clause(features[0])},',
      'Seek out ${clause(features[0])},',
    ];
    final questions = [
      'Which plant am I?',
      'Can you name me?',
      'Do you know what I am?',
      'What could I be?',
    ];

    final lines = <String>[
      openings[rng.nextInt(openings.length)],
      'with ${clause(features.length > 1 ? features[1] : features[0])},',
      'and ${clause(features.length > 2 ? features[2] : features[0])}.',
      questions[rng.nextInt(questions.length)],
    ];

    // Safety net: if a feature happens to contain the plant's own name, drop
    // that word rather than give the answer away.
    final names = [
      ...species.commonName.toLowerCase().split(RegExp(r'[\s()]+')),
      ...species.scientificName.toLowerCase().split(' '),
    ].where((w) => w.length > 3).toSet();

    return lines.map((line) {
      var out = line;
      for (final name in names) {
        out = out.replaceAll(RegExp(name, caseSensitive: false), 'it');
      }
      return out;
    }).toList();
  }
}
